export const homeObjOne = {
    id: 'signup',
    LightBg: false,
    LightText: true,
    LightTextDesc: true,
    topLine: 'For Premium Restaurants',
    headLine:'Keep your income in order with Digital Menus',
    description: 'Dingbell helps you with the control of all processes in your restaurant, from client orders, until the interaction with your revenues',
    buttonLabel: 'Get Started',
    imgStart: false,
    alt:'aboutUs',
    dark: true,
    primary: true,
    darkText: false,
}
export const homeObjTwo = {
    id: 'createdby',
    LightBg: false,
    LightText: true,
    LightTextDesc: true,
    topLine: 'For Premium Restaurants',
    headLine:'Keep your income in order with Digital Menus',
    description: 'Dingbell helps you with the control of all processes in your restaurant, from client orders, until the interaction with your revenues',
    buttonLabel: 'Get Started',
    imgStart: false,
    alt:'aboutUs',
    dark: true,
    primary: true,
    darkText: false,
}
