export const ActionTypes = {
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_LABELS: "GET_LABELS",
  GET_TABLES: "GET_TABLES",
  GET_MENU: "GET_MENU",
  GET_ORDERS: "GET_ORDERS",
  GET_USER: "GET_USER",
  FILTER_MENU_BY_CATEGORY: "FILTER_MENU_BY_CATEGORY",
  FILTER_MENU_BY_LABELS: "FILTER_MENU_BY_LABELS",
  ADD_ORDER: "ADD_ORDER",
  REMOVE_ORDER: "REMOVE_ORDER"
}