export const ActionTypes = {
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_LABELS: "GET_LABELS",
  GET_TABLES: "GET_TABLES",
  GET_MENU: "GET_MENU",
  GET_ORDERS: "GET_ORDERS",
  GET_USER: "GET_USER",
  GET_CART: "GET_CART",
  GET_PRODUCTS_BY_NAME: "GET_PRODUCTS_BY_NAME",
  FILTER_MENU_BY_CATEGORY: "FILTER_MENU_BY_CATEGORY",
  FILTER_MENU_BY_LABELS: "FILTER_MENU_BY_LABELS",
  ADD_ORDER: "ADD_ORDER",
  ADD_PRODUCT: "ADD_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  ADD_ORDER_TO_CART: "ADD_ORDER_TO_CART",
  ADD_COMMENT: "ADD_COMMENT",
  HIDE_SIDEBAR: "HIDE_SIDEBAR",
  POST_ORDER: "POST_ORDER"
}
